PATHS:
# C:\Users\PaulDS3\Downloads\project
  RAW_DATA: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\data\'                                       # Path containing all 3 raw datasets (Mila, Figure 1, RSNA)
  MILA_DATA: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\data\covid-chestxray-dataset\'              # Path of Mila dataset https://github.com/ieee8023/covid-chestxray-dataset
  FIGURE1_DATA: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\data\Figure1-COVID-chestxray-dataset\'   # Path of Figure 1 dataset https://github.com/agchung/Figure1-COVID-chestxray-dataset
  RSNA_DATA: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\data\rsna\'                                 # Path of RSNA dataset https://www.kaggle.com/c/rsna-pneumonia-detection-challenge
  PROCESSED_DATA: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\src\data\data\processed\'
  TRAIN_SET: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\src\data\data\processed\train_set.csv'
  VAL_SET: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\src\data\data\processed\val_set.csv'
  TEST_SET: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\src\data\data\processed\test_set.csv'
  IMAGES: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\documents\generated_images\'
  LOGS: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\results\logs\'
  MODEL_WEIGHTS: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\results\models\'
  MODEL_TO_LOAD: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\results\models\model20201109-115150.h5'
  LIME_EXPLAINER: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\interpretability\lime_explainer.pkl'
  OUTPUT_CLASS_INDICES: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\interpretability\output_class_indices.pkl'
  BATCH_PRED_IMGS: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\data\Figure1-COVID-chestxray-dataset\images\'
  # changed from custom test dir 'C:\Users\PaulDS3\Downloads\project\covid_cxr\src\data\data\processed\test'
  BATCH_PREDS: 'C:\Users\PaulDS3\Downloads\project\covid_cxr\results\predictions\'

DATA:
  IMG_DIM: [224, 224]
  VIEWS: ['PA', 'AP']
  VAL_SPLIT: 0.08
  TEST_SPLIT: 0.1
  NUM_RSNA_IMGS: 950 # 1000
  CLASSES: ['non-COVID-19', 'COVID-19']                   # Classes for binary classification
  #CLASSES: ['normal', 'COVID-19', 'other_pneumonia']     # Classes for multiclass classification (3 classes)

TRAIN:
  CLASS_MODE: 'binary'                                    # One of {'binary', 'multiclass'}
  MODEL_DEF: 'dcnn_resnet'                                # One of {'dcnn_resnet', 'resnet50v2', 'resnet101v2'}
  CLASS_MULTIPLIER: [0.15, 1.0]                           # Class multiplier for binary classification
  #CLASS_MULTIPLIER: [0.4, 1.0, 0.4]                      # Class multiplier for multiclass classification (3 classes)
  EXPERIMENT_TYPE: 'single_train'                         # One of {'single_train', 'multi_train', 'hparam_search'}
  BATCH_SIZE: 32
  EPOCHS: 100  # 200
  THRESHOLDS: 0.5                                         # Can be changed to list of values in range [0, 1]
  PATIENCE: 20
  IMB_STRATEGY: 'random_oversample'       # One of {'class_weight', 'random_oversample'} **changed from class_weights!
  METRIC_PREFERENCE: ['precision', 'recall', 'auc', 'loss'] # orignally ['auc', 'recall', ...]
  NUM_RUNS: 10
  NUM_GPUS: 1

NN:
  DCNN_BINARY:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 16  # 16
    FILTER_EXP_BASE: 3
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 3     # 3
    NODES_DENSE0: 64
    LR: 0.00001
    OPTIMIZER: 'adam'
    DROPOUT: 0.2       # 0.4
    L2_LAMBDA: 0.0001
  DCNN_MULTICLASS:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 16
    FILTER_EXP_BASE: 3
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 4
    NODES_DENSE0: 64
    LR: 0.0002
    OPTIMIZER: 'adam'
    DROPOUT: 0.2           # 0.40
    L2_LAMBDA: 0.0001

LIME:
  KERNEL_WIDTH: 1.75
  FEATURE_SELECTION: 'lasso_path'
  NUM_FEATURES: 1000
  NUM_SAMPLES: 1000
  COVID_ONLY: false

HP_SEARCH:
  METRICS: ['accuracy', 'loss', 'recall', 'precision', 'auc']
  COMBINATIONS: 50
  REPEATS: 2
  RANGES:
    KERNEL_SIZE: ['(3,3)', '(5,5)']     # Discrete range
    MAXPOOL_SIZE: ['(2,2)', '(3,3)']    # Discrete range
    INIT_FILTERS: [8, 16, 32]           # Discrete range
    FILTER_EXP_BASE: [2, 3]             # Int range
    NODES_DENSE0: [128, 256, 512, 1024] # Discrete range
    CONV_BLOCKS: [3, 8]                 # Int range
    DROPOUT: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]                 # Discrete range
    LR: [-5.0, -3.0]                    # Real range on log scale (10^x)
    OPTIMIZER: ['adam']                 # Discrete range
    L2_LAMBDA: [0.0, 0.00001, 0.0001, 0.001]    # Discrete range
    BATCH_SIZE: [16, 32]                # Discrete range
    IMB_STRATEGY: ['class_weight']      # Discrete range

PREDICTION:
  THRESHOLD: 0.5